### ISSUE TITLE
Cannot find module '@faker-js/faker' or its corresponding type declarations

### ISSUE THREAD

**Issue by Ikarus0013** [vantezzen/wrapped#4]
<img width="1192" alt="Screenshot 2023-06-15 at 15 15 49" src="https://github.com/vantezzen/wrapped/assets/99695698/a9053b2c-c7c9-492b-badc-f4b6c55b0787">

**Comment by vantezzen** [comment]
Have you installed the npm dependencies fully? Faker is declared as a dependency in package.json (https://github.com/vantezzen/wrapped/blob/d4fab5694f54894a4a295698e4a795031151c12f/package.json#LL14C6-L14C21) and should ship with its own type declarations
