### ISSUE TITLE
Doesn't read files on MS Edge

### ISSUE THREAD

**Issue by AngeloCore** [vantezzen/wrapped#5]
https://github.com/vantezzen/wrapped/assets/62988428/cad5c315-2924-4d27-8c53-6b24bac13c2f

**Comment by vantezzen** [comment]
Thank you for reporting this. Looks like it can read the file contents but can't process them. Can you take a look at the JavaScript console after uploading the file to look for any errors logged there?

**Comment by AngeloCore** [comment]
When i open json:
![image](https://github.com/vantezzen/wrapped/assets/62988428/0119eaa1-0a26-426a-b2dd-89fb5e3b1b60)

When i open zip:
![image](https://github.com/vantezzen/wrapped/assets/62988428/52b8b8d1-c66b-4bae-908f-a137d58557f9)

**Comment by AngeloCore** [comment]
@vantezzen looks like my json file was missing a bracket at the start for some reason, it works now
